### ISSUE TITLE
something not work in 1.0.28

### ISSUE THREAD

**Issue by Zavy86** [Zavy86/WikiDocs#139]
### Describe your issue

Blank pages

### Device and settings

https://demo.wikidocs.it/

### Steps to reproduce

just updated

### Screenshots (optional)

![image](https://github.com/Zavy86/WikiDocs/assets/2051811/76589033-4556-4ffd-b7ba-c8ed04200b59)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
```
Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/localhost/htdocs/libraries/parsedown-extra-0.8.1/ParsedownExtra.php:625 Stack trace: #0 /var/www/localhost/htdocs/libraries/parsedown-extra-0.8.1/ParsedownExtra.php(325): ParsedownExtra->processTag() #1 /var/www/localhost/htdocs/libraries/parsedown-1.8.0-beta-6/Parsedown.php(221): ParsedownExtra->blockMarkupComplete() #2 /var/www/localhost/htdocs/libraries/parsedown-1.8.0-beta-6/Parsedown.php(52): Parsedown->linesElements() #3 /var/www/localhost/htdocs/libraries/parsedown-extra-0.8.1/ParsedownExtra.php(46): Parsedown->textElements() #4 /var/www/localhost/htdocs/libraries/parsedown-extended-1.1.2-modified/ParsedownExtended.php(168): ParsedownExtra->text() #5 /var/www/localhost/htdocs/libraries/parsedown-extended-1.1.2-modified/ParsedownExtended.php(182): ParsedownExtended->body() #6 /var/www/localhost/htdocs/libraries/parsedown-plus-0.0.5/ParsedownPlus.php(58): ParsedownExtended->text() #7 /var/www/localhost/htdocs/template.inc.php(163): ParsedownPlus-> in /var/www/localhost/htdocs/libraries/parsedown-extra-0.8.1/ParsedownExtra.php on line 625
```

**Comment by Zavy86** [comment]
in my docker version i have add `apk add php-dom` and now it works.
I don't know why the problem is appear only now..

**Comment by leomoon** [comment]
oh yea I saw that too.

it needs php-dom and it is good to have php-xml too.
